/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mh.gui;

import com.mh.biz.Helado;
import com.mh.biz.MaquinaHelados;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hulkiniano
 */
public class Exec extends javax.swing.JFrame {

    /**
     * Creates new form Exec
     */
    public Exec() {
        initComponents();
        meterHelados();
        monedero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHelados = new javax.swing.JTable();
        jLabelTituloTabla = new javax.swing.JLabel();
        jButtonPedir = new javax.swing.JButton();
        jButtonSaldo = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelSaldo = new javax.swing.JLabel();
        jLabelMonedero = new javax.swing.JLabel();
        jLabelConst = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuAdmin = new javax.swing.JMenu();
        jMenuItemVentas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(7680, 4320));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1890, 1080));

        jTableHelados.setForeground(new java.awt.Color(153, 153, 255));
        jTableHelados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posición", "Nombre", "Precio", "Tipo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHelados.setColumnSelectionAllowed(true);
        jTableHelados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableHelados);
        jTableHelados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableHelados.getColumnModel().getColumnCount() > 0) {
            jTableHelados.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableHelados.getColumnModel().getColumn(1).setPreferredWidth(175);
            jTableHelados.getColumnModel().getColumn(2).setPreferredWidth(75);
            jTableHelados.getColumnModel().getColumn(3).setPreferredWidth(125);
            jTableHelados.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        jLabelTituloTabla.setBackground(new java.awt.Color(153, 51, 255));
        jLabelTituloTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloTabla.setLabelFor(jTableHelados);
        jLabelTituloTabla.setText("Venta de Helados");
        jLabelTituloTabla.setToolTipText("");

        jButtonPedir.setText("Pedir Helado");
        jButtonPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedirActionPerformed(evt);
            }
        });

        jButtonSaldo.setText("Añadir Saldo");
        jButtonSaldo.setToolTipText("");
        jButtonSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaldoActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.setToolTipText("");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabelSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSaldo.setText("Saldo:");
        jLabelSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelSaldo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelMonedero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMonedero.setText("0.00");

        jLabelConst.setText("€");

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemSalir);

        jMenuBar1.add(jMenuSalir);

        jMenuAdmin.setText("Administrador");
        jMenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdminActionPerformed(evt);
            }
        });

        jMenuItemVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemVentas.setText("Historial de ventas");
        jMenuItemVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVentasActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemVentas);

        jMenuBar1.add(jMenuAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTituloTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE))
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMonedero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelConst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPedir, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(774, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(jLabelTituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButtonPedir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMonedero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConst, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(150, 150, 150))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedirActionPerformed
        // TODO add your handling code here:
        PedirH ph = new PedirH(this, true);
        ph.setVisible(true);

    }//GEN-LAST:event_jButtonPedirActionPerformed

    private void jButtonSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaldoActionPerformed
        // TODO add your handling code here:
        InsertarMonedas im = new InsertarMonedas(this, true);
        im.setVisible(true);

    }//GEN-LAST:event_jButtonSaldoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        Cambio c = new Cambio(this, true);
        this.monedero();
        c.cambio(this.jLabelMonedero.getText());
        c.setVisible(true);

    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jMenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAdminActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        Cambio c = new Cambio(this, true);
        c.setVisible(true);

    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuItemVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVentasActionPerformed
        // TODO add your handling code here:
        VerVentas vv = new VerVentas(this, true);
        vv.ingreso(ingreso());
        vv.setVisible(true);
    }//GEN-LAST:event_jMenuItemVentasActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
        Cambio c = new Cambio(this, true);
        this.monedero();
        c.cambio(this.jLabelMonedero.getText());
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPedir;
    private javax.swing.JButton jButtonSaldo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelConst;
    private javax.swing.JLabel jLabelMonedero;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelTituloTabla;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemVentas;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHelados;
    // End of variables declaration//GEN-END:variables
    MaquinaHelados mh = new MaquinaHelados();

    public MaquinaHelados getMH() {
        return mh;
    }

    public void setMH(MaquinaHelados mh) {
        this.mh = mh;
    }

    public void meterHelados() {
        DefaultTableModel m = (DefaultTableModel) this.jTableHelados.getModel();
        m.setNumRows(0);
        try {
            ArrayList<Helado> l = mh.listaHelados();
            System.out.println("Helados recuperados: " + l.size());
            for (Helado helado : l) {
                String pre = String.valueOf(helado.getPrecio());
                if (pre.length() == 3) {
                    Object[] o = {helado.getPosicion(), helado.getNombre(), helado.getPrecio() + "0 €", helado.getTipo(), helado.getCantidad()};
                    m.addRow(o);
                } else {
                    Object[] o = {helado.getPosicion(), helado.getNombre(), helado.getPrecio() + " €", helado.getTipo(), helado.getCantidad()};
                    m.addRow(o);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void monedero() {
        this.jLabelMonedero.setText(String.valueOf(mh.getMonedero()));
        if (this.jLabelMonedero.getText().length() <= 3) {
            this.jLabelMonedero.setText(mh.getMonedero() + "0");
        } else if (mh.getMonedero() == 0){
            this.jLabelMonedero.setText(mh.getMonedero() + "00");
        }
    }
    public String ingreso() {
        String ing = String.valueOf(this.getMH().getIngresos());
        return ing;
    }
}
